# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# images here when I started the rails app
Image.create(path: "amalgam.jpg", name: "Amalgam")
Image.create(path: "blood.jpg", name: "Blood")
Image.create(path: "brithday.jpg", name: "Brithday")
Image.create(path: "dab.jpg", name: "Dab")
Image.create(path: "emotions.jpg", name: "Emotions")
Image.create(path: "extra_thicc.jpg", name: "Extra T h i c c")
Image.create(path: "facebook.jpg", name: "Facebook")
Image.create(path: "fat_furry_slut.jpg", name: "Fat Furry Slut")
Image.create(path: "feed.jpg", name: "Feed")
Image.create(path: "furry.jpg", name: "Furries")
Image.create(path: "garfeld.jpg", name: "Garfeld")
Image.create(path: "garfield_eats.jpg", name: "He Eats, Jon")
Image.create(path: "garfield_fieri.jpg", name: "Guyfield Fieri")
Image.create(path: "garsans.jpg", name: "Garçans")
Image.create(path: "gavel.jpg", name: "Justice")
Image.create(path: "greed.jpg", name: "Greed")
Image.create(path: "happy_bday_owen.jpg", name: "Wenny's Cake")
Image.create(path: "hey_liberals.jpg", name: "Hey Liberals")
Image.create(path: "homework.jpg", name: "Homework")
Image.create(path: "homo.jpg", name: "Desire")
Image.create(path: "hurt.jpg", name: "Hurt")
Image.create(path: "japanese.jpg", name: "Japanese")
Image.create(path: "jon_i_can_smell_you.jpg", name: "Essence of Jon")
Image.create(path: "love.jpg", name: "Love")
Image.create(path: "meesa.jpg", name: "Jar Gar")
Image.create(path: "mondays.jpg", name: "Mondays")
Image.create(path: "more_sexy.jpg", name: "Who Ordered Lasagne")
Image.create(path: "musical.jpg", name: "Musical")
Image.create(path: "number_5.jpg", name: "Number 5")
Image.create(path: "pepe.jpg", name: "Pepe")
Image.create(path: "pizza.jpg", name: "Pizza")
Image.create(path: "poke.jpg", name: "Poké")
Image.create(path: "potatofield.jpg", name: "Potatofield")
Image.create(path: "quoi.jpg", name: "Epic")
Image.create(path: "require.jpg", name: "He Requires")
Image.create(path: "rib.jpg", name: "Ribs")
Image.create(path: "sans.jpg", name: "Sans Jon")
Image.create(path: "sexiest.jpg", name: "Sexiest")
Image.create(path: "sexy.jpg", name: "Sexy")
Image.create(path: "texan.jpg", name: "Texan")
Image.create(path: "thiccfield.jpg", name: "Thiccfield")
Image.create(path: "thique.jpg", name: "Thique")
Image.create(path: "toy.jpg", name: "Toy")
Image.create(path: "vn.jpg", name: "VN")
Image.create(path: "what.jpg", name: "What")
Image.create(path: "wii.jpg", name: "Wii")
Image.create(path: "yin.jpg", name: "Yin")
Image.create(path: "zero_bids.jpg", name: "Zero Bids")
