# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# images here when I started the rails app

# SEEDS NOT FULLY LOADED YET: fill all "name" fields and reset db
Image.create(path: "amalgam.jpg", name: "Amalgam", author: "Site Owner")
Image.create(path: "blood.jpg", name: "Blood", author: "Site Owner")
Image.create(path: "brithday.jpg", name: "Brithday", author: "Site Owner")
Image.create(path: "dab.jpg", name: "Dab", author: "Site Owner")
Image.create(path: "emotions.jpg", name: "Emotions", author: "Site Owner")
Image.create(path: "extra_thicc.jpg", name: "Extra T h i c c", author: "Site Owner")
Image.create(path: "facebook.jpg", name: "Facebook", author: "Site Owner")
Image.create(path: "fat_furry_slut.jpg", name: "Fat Furry Slut", author: "Site Owner")
Image.create(path: "feed.jpg", name: "Feed", author: "Site Owner")
Image.create(path: "furry.jpg", name: "Furries", author: "Site Owner")
Image.create(path: "garfeld.jpg", name: "Garfeld", author: "Site Owner")
Image.create(path: "garfield_eats.jpg", name: "He Eats, Jon", author: "Site Owner")
Image.create(path: "garfield_fieri.jpg", name: "Guyfield Fieri", author: "Site Owner")
Image.create(path: "garsans.jpg", name: "Garçans", author: "Site Owner")
Image.create(path: "gavel.jpg", name: "Justice", author: "Site Owner")
Image.create(path: "greed.jpg", name: "Greed", author: "Site Owner")
Image.create(path: "happy_bday_owen.jpg", name: "Wenny's Cake", author: "Site Owner")
Image.create(path: "hey_liberals.jpg", name: "Hey Liberals", author: "Site Owner")
Image.create(path: "homework.jpg", name: "Homework", author: "Site Owner")
Image.create(path: "homo.jpg", name: "Desire", author: "Site Owner")
Image.create(path: "hurt.jpg", name: "Hurt", author: "Site Owner")
Image.create(path: "japanese.jpg", name: "Japanese", author: "Site Owner")
Image.create(path: "jon_i_can_smell_you.jpg", name: "Essence of Jon", author: "Site Owner")
Image.create(path: "love.jpg", name: "Love", author: "Site Owner")
Image.create(path: "meesa.jpg", name: "Jar Gar", author: "Site Owner")
Image.create(path: "mondays.jpg", name: "Mondays", author: "Site Owner")
Image.create(path: "more_sexy.jpg", name: "Who Ordered Lasagne", author: "Site Owner")
Image.create(path: "musical.jpg", name: "Musical", author: "Site Owner")
Image.create(path: "number_5.jpg", name: "Number 5", author: "Site Owner")
Image.create(path: "pepe.jpg", name: "Pepe", author: "Site Owner")
Image.create(path: "pizza.jpg", name: "Pizza", author: "Site Owner")
Image.create(path: "poke.jpg", name: "Poké", author: "Site Owner")
Image.create(path: "potatofield.jpg", name: "Potatofield", author: "Site Owner")
Image.create(path: "quoi.jpg", name: "Epic", author: "Site Owner")
Image.create(path: "require.jpg", name: "He Requires", author: "Site Owner")
Image.create(path: "rib.jpg", name: "Ribs", author: "Site Owner")
Image.create(path: "sans.jpg", name: "Sans Jon", author: "Site Owner")
Image.create(path: "sexiest.jpg", name: "Sexiest", author: "Site Owner")
Image.create(path: "sexy.jpg", name: "Sexy", author: "Site Owner")
Image.create(path: "texan.jpg", name: "Texan", author: "Site Owner")
Image.create(path: "thiccfield.jpg", name: "Thiccfield", author: "Site Owner")
Image.create(path: "thique.jpg", name: "Thique", author: "Site Owner")
Image.create(path: "toy.jpg", name: "Toy", author: "Site Owner")
Image.create(path: "vn.jpg", name: "VN", author: "Site Owner")
Image.create(path: "what.jpg", name: "What", author: "Site Owner")
Image.create(path: "wii.jpg", name: "Wii", author: "Site Owner")
Image.create(path: "yin.jpg", name: "Yin", author: "Site Owner")
Image.create(path: "zero_bids.jpg", name: "Zero Bids", author: "Site Owner")
